### ISSUE TITLE
GELF messages are not being sent with timestamp

### ISSUE THREAD

**Issue by vierno** [tsuru/bs#29]
The implementation of the GELF messages does not include the timestamp telling when the message was created, this can lead to misinformation in scenarios where the message is not processed immediately.

Code: https://github.com/tsuru/bs/blob/649c33333f52ab27583b2bcb51f3cea15fe396ba/log/gelfforwarder.go#L64

I believe the field we are missing this field:
https://github.com/Graylog2/go-gelf/blob/v1/gelf/writer.go#L54

**Comment by cezarsa** [comment]
Fixed by #30. Thanks @vierno !
