### ISSUE TITLE
failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by keymon** [tsuru/bs#4]
Today we upgrade an environment which restart the bs process, and now we are hitting [this kind of error](http://blog.cloud66.com/x509-error-when-using-https-inside-a-docker-container/):

```
2015/11/09 17:49:30 [WARNING] invalid interval "". Using the default value of 60 seconds
2015/11/09 17:49:30 [WARNING] invalid metrics interval "". Using the default value of 60 seconds
2015/11/09 17:49:30 Unable to initialize log forwarder: x509: failed to load system roots and no roots provided
```

If you something this, it fixes the issue:

```
docker run -e "DOCKER_ENDPOINT=http://1.2.3.4:4243" -e "TSURU_ENDPOINT=https://api.example.com:443/" -e "TSURU_TOKEN=fffffffffff" -e "SYSLOG_LISTEN_ADDRESS=udp://0.0.0.0:1514" -e "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"  --entrypoint "bash" tsuru/bs:v1 -c 'apt-get update && apt-get install -y ca-certificates && /bin/bs'
```

I think we need to install the ca-certificates in the image.

Also, maybe we should pin the versions

**Comment by keymon** [comment]
The issue is that in the commit https://github.com/tsuru/bs/commit/37b137a4aa5bc87170ffd4fd442aefcf298defa1#diff-3254677a7917c6c01f55212f86c57fbfL7 we don't install `wget`, and one of the dependencies of `wget` was `ca-certificates`. As that is missing, we get that error.

You can check that installing wget, works OK:

```
docker run -e "DOCKER_ENDPOINT=http://1.2.3.4:4243" -e "TSURU_ENDPOINT=https://api.example.com:443/" -e "TSURU_TOKEN=fffffffffff" -e "SYSLOG_LISTEN_ADDRESS=udp://0.0.0.0:1514" -e "PATH=/go/bin:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"  --entrypoint "bash" tsuru/bs:v1 -c 'apt-get update && apt-get install -y wget && /bin/bs' 
```

**Comment by fsouza** [comment]
@keymon thanks for reporting, I'm on it.

Are you using Docker Registry 2? If so, tsuru should pin bs version automatically.

**Comment by fsouza** [comment]
@keymon it should be fixed now, can you upgrade your bs version and try again?

**Comment by keymon** [comment]
Thx @fsouza that was really fast.

We upgraded and everything is working now.  We are all the time destroying and creating the environment for testing, including the registry, so we always get the latest versions, but I will check about using a shared registry 2.

Thx! :)
