### ISSUE TITLE
Host system wide metrics

### ISSUE THREAD

**Issue by andrestc** [tsuru/bs#5]
bs should collect and send system wide metrics(load, mem, cpu etc) about its host.

**Comment by andrestc** [comment]
This feature was added in bs in 25e3ea6cf3455159bd626a8cbf454c7cd813ef9e and in Tsuru in [5db7e95](https://github.com/tsuru/tsuru/commit/5db7e9597f360534acbb492a806dd8d74bab23f9).

**Comment by fsouza** [comment]
<img src='https://media.giphy.com/media/slA1wSjo4RZE4/giphy.gif'>
